config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :badges_users, only: :index

  resources :reviews, only: %i[new create]
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badges_users
  has_many :users, through: :badges_users
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update]
  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule, :rule_attribute)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/views/admin/badges/_badge.html.slim
tr
  td = link_to badge.title, admin_badge_path(badge.id)
  td = image_tag(badge.image_url, size: '26x26')

app/views/admin/badges/_form.html.slim
= form_with model: [:admin ,@badge] do |f|
  p = f.label 'Title'
  p = f.text_field :title
  p = f.label 'Image url'
  p = f.text_field :image_url
  p = f.label 'Rules'
  p = f.select :rule, [["За успешное прохождение всех тестов из категории", 'all_category_tests'],
                       ["За успешное прохождение теста с первой попытки", 'first_try_test'],
                       ["За успешное прохождение всех тестов уровня", 'one_level_tests']]
  p = f.label 'Rule attributes'
  p = f.select :rule_attribute, {"Категории тестов" => ["Backend", "Frontend", "Database"],
                                 "Уровни тестов" => ["1", "2", "3", "4", "5"]}, { include_blank: true }
  p = f.submit

app/views/admin/badges/edit.html.slim
h3 Edit badge

= render 'form'

app/views/admin/badges/index.html.slim
div class='container'
  h3 Badges

  p = link_to 'New_Badges', new_admin_badge_path

  div class='col col-md-7'
    table class='table'
      thead
        tr
          th Название
          th Награда

      = render @badges

app/views/admin/badges/new.html.slim
h3 New badge

= render 'form'

app/views/admin/badges/show.html.slim
h3 Награда #{@badge.title}

p = @badge.rule
p = @badge.rule_attribute

= link_to 'Редактирвать', edit_admin_badge_path(@badge.id)