config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :badges_users, only: :index

  resources :reviews, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_THRESHOLDS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: :create

  scope :successfully_passed, -> { where(success: true) }

  def accept!(answer_ids)
    self.correct_questions += 1  if correct_answer?(answer_ids)
    set_next_question
    save!
  end

  def completed?
    self.current_question.nil?
  end

  def time_to_pass
    test.timer * 60
  end

  def time_has_expired?
    last_minutes = (Time.current - self.created_at) / 60

    last_minutes >= time_to_pass if test.timer
  end

  def result
    correct_questions = self.correct_questions.to_f
    result = (correct_questions / test.questions.size) * 100
    result.round(2)
  end

  def update_success!
    if result > PASSING_THRESHOLDS
      self.update!(success: true)
    end
  end

  def check_passing
  end

  private

  def set_next_question
    self.current_question = next_question
  end

  def before_validation_set_current_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %w[show result update]

  def show
  end

  def result
    CheckBadges.new(test_passage: @test_passage).call
  end

  def update
    @test_passage.accept!(params['answer_ids'])

    if @test_passage.completed? || @test_passage.time_has_expired?
      TestsMailer.completed_test(@test_passage).deliver_now

      @test_passage.update_success!

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def position_current_question(test_passage)
    if test_passage.test.questions.any?
      test_passage.test.questions.index(test_passage.current_question) + 1
    end
  end
end

app/views/test_passages/result.html.slim
p The #{t('.header', title: @test_passage.test.title)}

- if @test_passage.success?
  div style='color: green'
    p Вы успешно прошли тест
    p Ваш процент прохождения #{@test_passage.result}%
- else
  div style='color: red'
    p Вы не прошли тест
    p Ваш процент прохождения #{@test_passage.result}%

= link_to 'Back', tests_path

app/views/test_passages/show.html.slim
div class='container'
  div class='row'
    div class='col col-md-7'
      = content_tag :h3, "Passing the #{@test_passage.test.title} Test",
        class: 'test_passage',
        data: { question_count: @test_passage.test.questions.count,
                number_current_question: position_current_question(@test_passage) }

      b #{@test_passage.current_question.body}

      = form_with url: test_passage_path(@test_passage), method: :put do |form|
        = form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b|
          p
            = b.check_box id: "answer_ids_#{b.object.id}"
            = b.label
        p
        p #{position_current_question(@test_passage)}-й вопрос из #{@test_passage.test.questions.count}
        p class='progress-btn'
          = form.submit 'Next question'
      p = button_to 'Create Gist', gists_path(test_passage_id: @test_passage)
    div class='col col-md-5'
      h3 Прохождение теста
      div class='progress-bar'
        div class='progress-bar-inner'
      h4 Время
      = content_tag :h4, 00,
        class: 'timer',
        data: { test_timer: @test_passage.test.timer, root_url: root_url }