config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :badges_users, only: :index

  resources :reviews, only: %i[new create]
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, dependent: :destroy

  validate :validate_answers_count

  scope :correct_answers, -> { where(correct: true) }

  def validate_answers_count
    if question.answers.size > 4
      errors.add(:answer, "должно быть от 1 до 4 ответов")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badges_users
  has_many :users, through: :badges_users
end

app/models/badges_user.rb
class BadgesUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  INFINITY_LEVEL = Float::INFINITY

  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level, message: "Тест с таким названием и уровнем уже существует" }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  scope :by_category, ->(category_name) do
    joins(:category)
    .where(category: { title: category_name })
  end

  scope :by_level, ->(level) do
    where(level: level)
  end

  scope :easy_level, -> { where(level: 0..1) }
  scope :middle_level, -> { where(level: 2..4) }
  scope :hard_level, -> { where(level: 4..INFINITY_LEVEL) }
  scope :displayed, -> { where(displayed: true) }

  class << self
    def titles_by_category(category_name)
      by_category(category_name).order(title: :desc).pluck(:title)
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_THRESHOLDS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: :create

  scope :successfully_passed, -> { where(success: true) }

  def accept!(answer_ids)
    self.correct_questions += 1  if correct_answer?(answer_ids)
    set_next_question
    save!
  end

  def completed?
    self.current_question.nil?
  end

  def time_to_pass
    test.timer * 60
  end

  def time_has_expired?
    last_minutes = (Time.current - self.created_at) / 60

    last_minutes >= time_to_pass if test.timer
  end

  def result
    correct_questions = self.correct_questions.to_f
    result = (correct_questions / test.questions.size) * 100
    result.round(2)
  end

  def update_success!
    if result > PASSING_THRESHOLDS
      self.update!(success: true)
    end
  end

  def check_passing
  end

  private

  def set_next_question
    self.current_question = next_question
  end

  def before_validation_set_current_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]{2,}\z/i

  has_many :author_tests, class_name: 'Test'
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :badges_users
  has_many :badges, through: :badges_users

  validates :email, format: { with: EMAIL_REGEXP, message: "не является корректным адресом электронной почты" }
  validates :email, uniqueness: true

  def find_tests_by_level(level)
    self.tests.find_by(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.type == 'Admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def after_sign_in_path_for(resource)
    flash[:notice] = "Привет, #{resource.first_name}!"

    if resource.admin?
      admin_tests_path
    else
      super
    end
  end

  def default_url_options
    { lang: I18n.locale } unless I18n.locale == params[:lang]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end
end

app/controllers/badges_users_controller.rb
class BadgesUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges_users = current_user.badges_users
  end
end

app/controllers/gists_controller.rb
class GistsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_test_passage
  before_action :init_client

  def create
    question = @test_passage.current_question

    gist = GistQuestionService.new(
      question: question,
      client: @client
    ).call

    if @client.success?
      Gist.create!(
        url: gist[:html_url],
        question_id: question.id,
        user_id: current_user.id
      )

      flash_options = { notice: t('.success', gist_link: gist[:html_url]) }
    else
      { alert: t('.failure')}
    end

    redirect_to @test_passage, flash_options
  end

  private

  def init_client
    @client = GitHubClient.new
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
    ReviewsMailer.send_reviews(email: params[:email], body: params[:body]).deliver_now
    redirect_to new_review_path, notice: 'Ваше сообщение отправлено!'
  end

  private

  def reviews_params
    params.require(:reviews).permit(:body, :email)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.displayed
  end


  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def view_flash(key)
    content_tag(:p, flash[key], class: "#{key}-flash")
  end
end

app/helpers/test_helper.rb
module TestHelper
  def view_test_title(question)
    test = question.test

    if question.new_record?
      "#{test.title} Create question"
    else
      "#{test.title} Edit question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def position_current_question(test_passage)
    if test_passage.test.questions.any?
      test_passage.test.questions.index(test_passage.current_question) + 1
    end
  end
end

app/helpers/user_data_helper.rb
module UserDataHelper
  def github_url(author, repo)
    link_to 'проект TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end
end

app/views/layouts/admin.html.slim
<!DOCTYPE html>
html
  head
    title AdminPannel TestGuru
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'form_inline'


  body
    = render 'shared/flash'
    = render 'admin/tests/nav'

    div class='container'
      = yield

    script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title TestGuru
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'sorting'
    = javascript_pack_tag 'new_registrations_form'
    = javascript_pack_tag 'progress_bar'
    = javascript_pack_tag 'timer'
    script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"


  body
    = render 'shared/nav'

    div class='container'
      = render 'shared/flash'

      = yield
  footer
    p #{current_year} г.
    p Автор проекта - Козельский Вадим
    p = github_url('VadimKo28', 'TestGuru')
    p TestGuru это платформа для создания и прохождения учебных тестов.
    p = link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com/', target: '_blank'
    p = link_to 'Оставить отзыв', new_review_path

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
    = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id }
      h2 = "#{pluralize(resource.errors.count, 'error')} detected:"
      = t('.header', count: resource.errors.count)
      ul
        - resource.errors.full_messages.each do |message|
          li = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  div class="alert alert-primary" role="alert"
    = content_tag :p, message.html_safe

app/views/shared/_nav.html.slim
nav class='navbar navbar-light bg-light'
  = link_to 'Test Guru', tests_path, class: 'navbar-brand'
  = link_to 'Мои награды', badges_users_path, class: 'navbar-brand'

  span class='navbar-text'
    - if user_signed_in?
      p Welcome #{current_user.email} Guru
      = button_to 'Sign Out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sign_in', new_user_registration_path
      = link_to 'Log_in', new_user_session_path