config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :badges_users, only: :index

  resources :reviews, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  before_action :find_test, only: %w[new create]
  before_action :find_question, only: %w[show destroy edit update]

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)


    if @question.save
      redirect_to [:admin, @question]
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  def destroy
    @question.delete
    redirect_to test_questions_path(@question.test)
  end

  private

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/views/admin/questions/_form.html.slim
h2 = view_test_title(@question)

= form_with model: [:admin, @test, @question] do |form|

  = render 'shared/errors', resource: @question

  p = form.label :body, 'Body'

  p = form.text_field :body

  p = form.submit

app/views/admin/questions/_question.html.slim
p = link_to "#{question.body}",  admin_question_path(id: question.id, test_id: @test.id )

app/views/admin/questions/edit.html.slim
= render 'form'

p = link_to 'Back', admin_test_path(@question.test)

app/views/admin/questions/new.html.slim
= render 'form'

p = link_to 'Back', admin_tests_path

app/views/admin/questions/show.html.slim
p Вопрос #{@question.body} теста #{@question.test.title}

p = link_to 'Edit', edit_admin_question_path(test_id: @question.test.id, id: @question.id)
p = button_to 'Delete', admin_question_path(@question.id), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить этот вопрос?' }
p = link_to 'Back', admin_test_path(@question.test)

p Ответы

- @question.answers.each do |answer|
  p = link_to answer.body, admin_answer_path(answer.id)

p = button_to "Создать ответ", new_admin_question_answer_path(question_id: @question.id), method: :get